# Mostly system specific, if you can handle more or less, change these for your needs
org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=1

# Minecraft
minecraft_version=26.2

# CIT Resewn
mod.version=1.0.0
mod.jarname=cit-resewn
mod.target-mc=>=26.2
publish.target-mc=26.2
publish.modrinth.id=8auYYPlH
publish.curseforge.id=1547171

# Dependencies
deps.fabric-loader=0.19.2
deps.fabric-api=0.153.0+26.2
deps.sponge-mixin=0.15.3+mixin.0.8.7
deps.modmenu=19.0.0-alpha.1
deps.cloth-config=26.2.155
