# Mostly system specific, if you can handle more or less, change these for your needs
org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=1

# Minecraft
minecraft_version=26.3

# CIT Resewn
mod.version=1.0.0
mod.jarname=cit-resewn
mod.target-mc=>=26.3

# Dependencies
deps.fabric-loader=0.19.5
deps.fabric-api=0.160.4+26.3
deps.sponge-mixin=0.15.3+mixin.0.8.7
deps.modmenu=21.0.0-beta.1
deps.cloth-config=26.2.155
