name: Gradle 提交自动构建

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 更改为 write，允许创建 Release 和上传资产
      packages: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - uses: gradle/actions/setup-gradle@v5.0.0
      
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: gradle-build-arm
          path: build/libs/*.jar

      - name: 发布到 GitHub Packages
        if: github.event_name == 'release'
        run: ./gradlew publish --parallel --build-cache
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 自动发布到 GitHub Releases
        uses: softprops/action-gh-release@v2
        if: |
          github.event_name == 'release' || 
          github.event_name == 'push' || 
          github.event_name == 'workflow_dispatch'
        with:
          # 如果是 push 或手动触发，自动生成一个临时 tag（例如：v-commitSHA）
          tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name || format('v-{0}', github.sha) }}
          name: ${{ github.event_name == 'release' && github.event.release.name || format('自动构建发布 - {0}', github.sha) }}
          draft: false
          prerelease: ${{ github.event_name != 'release' }} # 非正式 release 触发时，标记为预发布
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
